package com.google.android.gms.internal.mlkit_common;

import android.support.v4.media.a;
import f0.b0;
import java.util.HashMap;
import sa.b;
import sa.c;
import sa.d;

/* compiled from: com.google.mlkit:common@@18.7.0 */
final class zzgh implements c {
    private static final b zzA;
    private static final b zzB;
    private static final b zzC;
    private static final b zzD;
    private static final b zzE;
    private static final b zzF;
    private static final b zzG;
    private static final b zzH;
    private static final b zzI;
    private static final b zzJ;
    private static final b zzK;
    private static final b zzL;
    private static final b zzM;
    private static final b zzN;
    private static final b zzO;
    private static final b zzP;
    private static final b zzQ;
    private static final b zzR;
    private static final b zzS;
    private static final b zzT;
    private static final b zzU;
    private static final b zzV;
    private static final b zzW;
    private static final b zzX;
    private static final b zzY;
    private static final b zzZ;
    public static final zzgh zza = new zzgh();
    private static final b zzaA;
    private static final b zzaB;
    private static final b zzaC;
    private static final b zzaD;
    private static final b zzaE;
    private static final b zzaF;
    private static final b zzaG;
    private static final b zzaH;
    private static final b zzaI;
    private static final b zzaJ;
    private static final b zzaK;
    private static final b zzaL;
    private static final b zzaM;
    private static final b zzaN;
    private static final b zzaO;
    private static final b zzaP;
    private static final b zzaQ;
    private static final b zzaR;
    private static final b zzaS;
    private static final b zzaT;
    private static final b zzaU;
    private static final b zzaV;
    private static final b zzaW;
    private static final b zzaX;
    private static final b zzaY;
    private static final b zzaa;
    private static final b zzab;
    private static final b zzac;
    private static final b zzad;
    private static final b zzae;
    private static final b zzaf;
    private static final b zzag;
    private static final b zzah;
    private static final b zzai;
    private static final b zzaj;
    private static final b zzak;
    private static final b zzal;
    private static final b zzam;
    private static final b zzan;
    private static final b zzao;
    private static final b zzap;
    private static final b zzaq;
    private static final b zzar;
    private static final b zzas;
    private static final b zzat;
    private static final b zzau;
    private static final b zzav;
    private static final b zzaw;
    private static final b zzax;
    private static final b zzay;
    private static final b zzaz;
    private static final b zzb;
    private static final b zzc;
    private static final b zzd;
    private static final b zze;
    private static final b zzf;
    private static final b zzg;
    private static final b zzh;
    private static final b zzi;
    private static final b zzj;
    private static final b zzk;
    private static final b zzl;
    private static final b zzm;
    private static final b zzn;
    private static final b zzo;
    private static final b zzp;
    private static final b zzq;
    private static final b zzr;
    private static final b zzs;
    private static final b zzt;
    private static final b zzu;
    private static final b zzv;
    private static final b zzw;
    private static final b zzx;
    private static final b zzy;
    private static final b zzz;

    static {
        zzbo g2 = a.g(1);
        HashMap hashMap = new HashMap();
        hashMap.put(g2.annotationType(), g2);
        zzb = new b("systemInfo", b0.z(hashMap));
        zzbo g10 = a.g(2);
        HashMap hashMap2 = new HashMap();
        hashMap2.put(g10.annotationType(), g10);
        zzc = new b("eventName", b0.z(hashMap2));
        zzbo g11 = a.g(37);
        HashMap hashMap3 = new HashMap();
        hashMap3.put(g11.annotationType(), g11);
        zzd = new b("isThickClient", b0.z(hashMap3));
        zzbo g12 = a.g(61);
        HashMap hashMap4 = new HashMap();
        hashMap4.put(g12.annotationType(), g12);
        zze = new b("clientType", b0.z(hashMap4));
        zzbo g13 = a.g(3);
        HashMap hashMap5 = new HashMap();
        hashMap5.put(g13.annotationType(), g13);
        zzf = new b("modelDownloadLogEvent", b0.z(hashMap5));
        zzbo g14 = a.g(20);
        HashMap hashMap6 = new HashMap();
        hashMap6.put(g14.annotationType(), g14);
        zzg = new b("customModelLoadLogEvent", b0.z(hashMap6));
        zzbo g15 = a.g(4);
        HashMap hashMap7 = new HashMap();
        hashMap7.put(g15.annotationType(), g15);
        zzh = new b("customModelInferenceLogEvent", b0.z(hashMap7));
        zzbo g16 = a.g(29);
        HashMap hashMap8 = new HashMap();
        hashMap8.put(g16.annotationType(), g16);
        zzi = new b("customModelCreateLogEvent", b0.z(hashMap8));
        zzbo g17 = a.g(5);
        HashMap hashMap9 = new HashMap();
        hashMap9.put(g17.annotationType(), g17);
        zzj = new b("onDeviceFaceDetectionLogEvent", b0.z(hashMap9));
        zzbo g18 = a.g(59);
        HashMap hashMap10 = new HashMap();
        hashMap10.put(g18.annotationType(), g18);
        zzk = new b("onDeviceFaceLoadLogEvent", b0.z(hashMap10));
        zzbo g19 = a.g(6);
        HashMap hashMap11 = new HashMap();
        hashMap11.put(g19.annotationType(), g19);
        zzl = new b("onDeviceTextDetectionLogEvent", b0.z(hashMap11));
        zzbo g20 = a.g(79);
        HashMap hashMap12 = new HashMap();
        hashMap12.put(g20.annotationType(), g20);
        zzm = new b("onDeviceTextDetectionLoadLogEvent", b0.z(hashMap12));
        zzbo g21 = a.g(7);
        HashMap hashMap13 = new HashMap();
        hashMap13.put(g21.annotationType(), g21);
        zzn = new b("onDeviceBarcodeDetectionLogEvent", b0.z(hashMap13));
        zzbo g22 = a.g(58);
        HashMap hashMap14 = new HashMap();
        hashMap14.put(g22.annotationType(), g22);
        zzo = new b("onDeviceBarcodeLoadLogEvent", b0.z(hashMap14));
        zzbo g23 = a.g(48);
        HashMap hashMap15 = new HashMap();
        hashMap15.put(g23.annotationType(), g23);
        zzp = new b("onDeviceImageLabelCreateLogEvent", b0.z(hashMap15));
        zzbo g24 = a.g(49);
        HashMap hashMap16 = new HashMap();
        hashMap16.put(g24.annotationType(), g24);
        zzq = new b("onDeviceImageLabelLoadLogEvent", b0.z(hashMap16));
        zzbo g25 = a.g(18);
        HashMap hashMap17 = new HashMap();
        hashMap17.put(g25.annotationType(), g25);
        zzr = new b("onDeviceImageLabelDetectionLogEvent", b0.z(hashMap17));
        zzbo g26 = a.g(26);
        HashMap hashMap18 = new HashMap();
        hashMap18.put(g26.annotationType(), g26);
        zzs = new b("onDeviceObjectCreateLogEvent", b0.z(hashMap18));
        zzbo g27 = a.g(27);
        HashMap hashMap19 = new HashMap();
        hashMap19.put(g27.annotationType(), g27);
        zzt = new b("onDeviceObjectLoadLogEvent", b0.z(hashMap19));
        zzbo g28 = a.g(28);
        HashMap hashMap20 = new HashMap();
        hashMap20.put(g28.annotationType(), g28);
        zzu = new b("onDeviceObjectInferenceLogEvent", b0.z(hashMap20));
        zzbo g29 = a.g(44);
        HashMap hashMap21 = new HashMap();
        hashMap21.put(g29.annotationType(), g29);
        zzv = new b("onDevicePoseDetectionLogEvent", b0.z(hashMap21));
        zzbo g30 = a.g(45);
        HashMap hashMap22 = new HashMap();
        hashMap22.put(g30.annotationType(), g30);
        zzw = new b("onDeviceSegmentationLogEvent", b0.z(hashMap22));
        zzbo g31 = a.g(19);
        HashMap hashMap23 = new HashMap();
        hashMap23.put(g31.annotationType(), g31);
        zzx = new b("onDeviceSmartReplyLogEvent", b0.z(hashMap23));
        zzbo g32 = a.g(21);
        HashMap hashMap24 = new HashMap();
        hashMap24.put(g32.annotationType(), g32);
        zzy = new b("onDeviceLanguageIdentificationLogEvent", b0.z(hashMap24));
        zzbo g33 = a.g(22);
        HashMap hashMap25 = new HashMap();
        hashMap25.put(g33.annotationType(), g33);
        zzz = new b("onDeviceTranslationLogEvent", b0.z(hashMap25));
        zzbo g34 = a.g(8);
        HashMap hashMap26 = new HashMap();
        hashMap26.put(g34.annotationType(), g34);
        zzA = new b("cloudFaceDetectionLogEvent", b0.z(hashMap26));
        zzbo g35 = a.g(9);
        HashMap hashMap27 = new HashMap();
        hashMap27.put(g35.annotationType(), g35);
        zzB = new b("cloudCropHintDetectionLogEvent", b0.z(hashMap27));
        zzbo g36 = a.g(10);
        HashMap hashMap28 = new HashMap();
        hashMap28.put(g36.annotationType(), g36);
        zzC = new b("cloudDocumentTextDetectionLogEvent", b0.z(hashMap28));
        zzbo g37 = a.g(11);
        HashMap hashMap29 = new HashMap();
        hashMap29.put(g37.annotationType(), g37);
        zzD = new b("cloudImagePropertiesDetectionLogEvent", b0.z(hashMap29));
        zzbo g38 = a.g(12);
        HashMap hashMap30 = new HashMap();
        hashMap30.put(g38.annotationType(), g38);
        zzE = new b("cloudImageLabelDetectionLogEvent", b0.z(hashMap30));
        zzbo g39 = a.g(13);
        HashMap hashMap31 = new HashMap();
        hashMap31.put(g39.annotationType(), g39);
        zzF = new b("cloudLandmarkDetectionLogEvent", b0.z(hashMap31));
        zzbo g40 = a.g(14);
        HashMap hashMap32 = new HashMap();
        hashMap32.put(g40.annotationType(), g40);
        zzG = new b("cloudLogoDetectionLogEvent", b0.z(hashMap32));
        zzbo g41 = a.g(15);
        HashMap hashMap33 = new HashMap();
        hashMap33.put(g41.annotationType(), g41);
        zzH = new b("cloudSafeSearchDetectionLogEvent", b0.z(hashMap33));
        zzbo g42 = a.g(16);
        HashMap hashMap34 = new HashMap();
        hashMap34.put(g42.annotationType(), g42);
        zzI = new b("cloudTextDetectionLogEvent", b0.z(hashMap34));
        zzbo g43 = a.g(17);
        HashMap hashMap35 = new HashMap();
        hashMap35.put(g43.annotationType(), g43);
        zzJ = new b("cloudWebSearchDetectionLogEvent", b0.z(hashMap35));
        zzbo g44 = a.g(23);
        HashMap hashMap36 = new HashMap();
        hashMap36.put(g44.annotationType(), g44);
        zzK = new b("automlImageLabelingCreateLogEvent", b0.z(hashMap36));
        zzbo g45 = a.g(24);
        HashMap hashMap37 = new HashMap();
        hashMap37.put(g45.annotationType(), g45);
        zzL = new b("automlImageLabelingLoadLogEvent", b0.z(hashMap37));
        zzbo g46 = a.g(25);
        HashMap hashMap38 = new HashMap();
        hashMap38.put(g46.annotationType(), g46);
        zzM = new b("automlImageLabelingInferenceLogEvent", b0.z(hashMap38));
        zzbo g47 = a.g(39);
        HashMap hashMap39 = new HashMap();
        hashMap39.put(g47.annotationType(), g47);
        zzN = new b("isModelDownloadedLogEvent", b0.z(hashMap39));
        zzbo g48 = a.g(40);
        HashMap hashMap40 = new HashMap();
        hashMap40.put(g48.annotationType(), g48);
        zzO = new b("deleteModelLogEvent", b0.z(hashMap40));
        zzbo g49 = a.g(30);
        HashMap hashMap41 = new HashMap();
        hashMap41.put(g49.annotationType(), g49);
        zzP = new b("aggregatedAutomlImageLabelingInferenceLogEvent", b0.z(hashMap41));
        zzbo g50 = a.g(31);
        HashMap hashMap42 = new HashMap();
        hashMap42.put(g50.annotationType(), g50);
        zzQ = new b("aggregatedCustomModelInferenceLogEvent", b0.z(hashMap42));
        zzbo g51 = a.g(32);
        HashMap hashMap43 = new HashMap();
        hashMap43.put(g51.annotationType(), g51);
        zzR = new b("aggregatedOnDeviceFaceDetectionLogEvent", b0.z(hashMap43));
        zzbo g52 = a.g(33);
        HashMap hashMap44 = new HashMap();
        hashMap44.put(g52.annotationType(), g52);
        zzS = new b("aggregatedOnDeviceBarcodeDetectionLogEvent", b0.z(hashMap44));
        zzbo g53 = a.g(34);
        HashMap hashMap45 = new HashMap();
        hashMap45.put(g53.annotationType(), g53);
        zzT = new b("aggregatedOnDeviceImageLabelDetectionLogEvent", b0.z(hashMap45));
        zzbo g54 = a.g(35);
        HashMap hashMap46 = new HashMap();
        hashMap46.put(g54.annotationType(), g54);
        zzU = new b("aggregatedOnDeviceObjectInferenceLogEvent", b0.z(hashMap46));
        zzbo g55 = a.g(36);
        HashMap hashMap47 = new HashMap();
        hashMap47.put(g55.annotationType(), g55);
        zzV = new b("aggregatedOnDeviceTextDetectionLogEvent", b0.z(hashMap47));
        zzbo g56 = a.g(46);
        HashMap hashMap48 = new HashMap();
        hashMap48.put(g56.annotationType(), g56);
        zzW = new b("aggregatedOnDevicePoseDetectionLogEvent", b0.z(hashMap48));
        zzbo g57 = a.g(47);
        HashMap hashMap49 = new HashMap();
        hashMap49.put(g57.annotationType(), g57);
        zzX = new b("aggregatedOnDeviceSegmentationLogEvent", b0.z(hashMap49));
        zzbo g58 = a.g(69);
        HashMap hashMap50 = new HashMap();
        hashMap50.put(g58.annotationType(), g58);
        zzY = new b("pipelineAccelerationInferenceEvents", b0.z(hashMap50));
        zzbo g59 = a.g(42);
        HashMap hashMap51 = new HashMap();
        hashMap51.put(g59.annotationType(), g59);
        zzZ = new b("remoteConfigLogEvent", b0.z(hashMap51));
        zzbo g60 = a.g(50);
        HashMap hashMap52 = new HashMap();
        hashMap52.put(g60.annotationType(), g60);
        zzaa = new b("inputImageConstructionLogEvent", b0.z(hashMap52));
        zzbo g61 = a.g(51);
        HashMap hashMap53 = new HashMap();
        hashMap53.put(g61.annotationType(), g61);
        zzab = new b("leakedHandleEvent", b0.z(hashMap53));
        zzbo g62 = a.g(52);
        HashMap hashMap54 = new HashMap();
        hashMap54.put(g62.annotationType(), g62);
        zzac = new b("cameraSourceLogEvent", b0.z(hashMap54));
        zzbo g63 = a.g(53);
        HashMap hashMap55 = new HashMap();
        hashMap55.put(g63.annotationType(), g63);
        zzad = new b("imageLabelOptionalModuleLogEvent", b0.z(hashMap55));
        zzbo g64 = a.g(54);
        HashMap hashMap56 = new HashMap();
        hashMap56.put(g64.annotationType(), g64);
        zzae = new b("languageIdentificationOptionalModuleLogEvent", b0.z(hashMap56));
        zzbo g65 = a.g(60);
        HashMap hashMap57 = new HashMap();
        hashMap57.put(g65.annotationType(), g65);
        zzaf = new b("faceDetectionOptionalModuleLogEvent", b0.z(hashMap57));
        zzbo g66 = a.g(85);
        HashMap hashMap58 = new HashMap();
        hashMap58.put(g66.annotationType(), g66);
        zzag = new b("documentDetectionOptionalModuleLogEvent", b0.z(hashMap58));
        zzbo g67 = a.g(86);
        HashMap hashMap59 = new HashMap();
        hashMap59.put(g67.annotationType(), g67);
        zzah = new b("documentCroppingOptionalModuleLogEvent", b0.z(hashMap59));
        zzbo g68 = a.g(87);
        HashMap hashMap60 = new HashMap();
        hashMap60.put(g68.annotationType(), g68);
        zzai = new b("documentEnhancementOptionalModuleLogEvent", b0.z(hashMap60));
        zzbo g69 = a.g(55);
        HashMap hashMap61 = new HashMap();
        hashMap61.put(g69.annotationType(), g69);
        zzaj = new b("nlClassifierOptionalModuleLogEvent", b0.z(hashMap61));
        zzbo g70 = a.g(56);
        HashMap hashMap62 = new HashMap();
        hashMap62.put(g70.annotationType(), g70);
        zzak = new b("nlClassifierClientLibraryLogEvent", b0.z(hashMap62));
        zzbo g71 = a.g(57);
        HashMap hashMap63 = new HashMap();
        hashMap63.put(g71.annotationType(), g71);
        zzal = new b("accelerationAllowlistLogEvent", b0.z(hashMap63));
        zzbo g72 = a.g(62);
        HashMap hashMap64 = new HashMap();
        hashMap64.put(g72.annotationType(), g72);
        zzam = new b("toxicityDetectionCreateEvent", b0.z(hashMap64));
        zzbo g73 = a.g(63);
        HashMap hashMap65 = new HashMap();
        hashMap65.put(g73.annotationType(), g73);
        zzan = new b("toxicityDetectionLoadEvent", b0.z(hashMap65));
        zzbo g74 = a.g(64);
        HashMap hashMap66 = new HashMap();
        hashMap66.put(g74.annotationType(), g74);
        zzao = new b("toxicityDetectionInferenceEvent", b0.z(hashMap66));
        zzbo g75 = a.g(65);
        HashMap hashMap67 = new HashMap();
        hashMap67.put(g75.annotationType(), g75);
        zzap = new b("barcodeDetectionOptionalModuleLogEvent", b0.z(hashMap67));
        zzbo g76 = a.g(66);
        HashMap hashMap68 = new HashMap();
        hashMap68.put(g76.annotationType(), g76);
        zzaq = new b("customImageLabelOptionalModuleLogEvent", b0.z(hashMap68));
        zzbo g77 = a.g(67);
        HashMap hashMap69 = new HashMap();
        hashMap69.put(g77.annotationType(), g77);
        zzar = new b("codeScannerScanApiEvent", b0.z(hashMap69));
        zzbo g78 = a.g(68);
        HashMap hashMap70 = new HashMap();
        hashMap70.put(g78.annotationType(), g78);
        zzas = new b("codeScannerOptionalModuleEvent", b0.z(hashMap70));
        zzbo g79 = a.g(70);
        HashMap hashMap71 = new HashMap();
        hashMap71.put(g79.annotationType(), g79);
        zzat = new b("onDeviceExplicitContentCreateLogEvent", b0.z(hashMap71));
        zzbo g80 = a.g(71);
        HashMap hashMap72 = new HashMap();
        hashMap72.put(g80.annotationType(), g80);
        zzau = new b("onDeviceExplicitContentLoadLogEvent", b0.z(hashMap72));
        zzbo g81 = a.g(72);
        HashMap hashMap73 = new HashMap();
        hashMap73.put(g81.annotationType(), g81);
        zzav = new b("onDeviceExplicitContentInferenceLogEvent", b0.z(hashMap73));
        zzbo g82 = a.g(73);
        HashMap hashMap74 = new HashMap();
        hashMap74.put(g82.annotationType(), g82);
        zzaw = new b("aggregatedOnDeviceExplicitContentLogEvent", b0.z(hashMap74));
        zzbo g83 = a.g(74);
        HashMap hashMap75 = new HashMap();
        hashMap75.put(g83.annotationType(), g83);
        zzax = new b("onDeviceFaceMeshCreateLogEvent", b0.z(hashMap75));
        zzbo g84 = a.g(75);
        HashMap hashMap76 = new HashMap();
        hashMap76.put(g84.annotationType(), g84);
        zzay = new b("onDeviceFaceMeshLoadLogEvent", b0.z(hashMap76));
        zzbo g85 = a.g(76);
        HashMap hashMap77 = new HashMap();
        hashMap77.put(g85.annotationType(), g85);
        zzaz = new b("onDeviceFaceMeshLogEvent", b0.z(hashMap77));
        zzbo g86 = a.g(77);
        HashMap hashMap78 = new HashMap();
        hashMap78.put(g86.annotationType(), g86);
        zzaA = new b("aggregatedOnDeviceFaceMeshLogEvent", b0.z(hashMap78));
        zzbo g87 = a.g(78);
        HashMap hashMap79 = new HashMap();
        hashMap79.put(g87.annotationType(), g87);
        zzaB = new b("smartReplyOptionalModuleLogEvent", b0.z(hashMap79));
        zzbo g88 = a.g(80);
        HashMap hashMap80 = new HashMap();
        hashMap80.put(g88.annotationType(), g88);
        zzaC = new b("textDetectionOptionalModuleLogEvent", b0.z(hashMap80));
        zzbo g89 = a.g(81);
        HashMap hashMap81 = new HashMap();
        hashMap81.put(g89.annotationType(), g89);
        zzaD = new b("onDeviceImageQualityAnalysisCreateLogEvent", b0.z(hashMap81));
        zzbo g90 = a.g(82);
        HashMap hashMap82 = new HashMap();
        hashMap82.put(g90.annotationType(), g90);
        zzaE = new b("onDeviceImageQualityAnalysisLoadLogEvent", b0.z(hashMap82));
        zzbo g91 = a.g(83);
        HashMap hashMap83 = new HashMap();
        hashMap83.put(g91.annotationType(), g91);
        zzaF = new b("onDeviceImageQualityAnalysisLogEvent", b0.z(hashMap83));
        zzbo g92 = a.g(84);
        HashMap hashMap84 = new HashMap();
        hashMap84.put(g92.annotationType(), g92);
        zzaG = new b("aggregatedOnDeviceImageQualityAnalysisLogEvent", b0.z(hashMap84));
        zzbo g93 = a.g(88);
        HashMap hashMap85 = new HashMap();
        hashMap85.put(g93.annotationType(), g93);
        zzaH = new b("imageQualityAnalysisOptionalModuleLogEvent", b0.z(hashMap85));
        zzbo g94 = a.g(89);
        HashMap hashMap86 = new HashMap();
        hashMap86.put(g94.annotationType(), g94);
        zzaI = new b("imageCaptioningOptionalModuleLogEvent", b0.z(hashMap86));
        zzbo g95 = a.g(90);
        HashMap hashMap87 = new HashMap();
        hashMap87.put(g95.annotationType(), g95);
        zzaJ = new b("onDeviceImageCaptioningCreateLogEvent", b0.z(hashMap87));
        zzbo g96 = a.g(91);
        HashMap hashMap88 = new HashMap();
        hashMap88.put(g96.annotationType(), g96);
        zzaK = new b("onDeviceImageCaptioningLoadLogEvent", b0.z(hashMap88));
        zzbo g97 = a.g(92);
        HashMap hashMap89 = new HashMap();
        hashMap89.put(g97.annotationType(), g97);
        zzaL = new b("onDeviceImageCaptioningInferenceLogEvent", b0.z(hashMap89));
        zzbo g98 = a.g(93);
        HashMap hashMap90 = new HashMap();
        hashMap90.put(g98.annotationType(), g98);
        zzaM = new b("aggregatedOnDeviceImageCaptioningInferenceLogEvent", b0.z(hashMap90));
        zzbo g99 = a.g(94);
        HashMap hashMap91 = new HashMap();
        hashMap91.put(g99.annotationType(), g99);
        zzaN = new b("onDeviceDocumentDetectionCreateLogEvent", b0.z(hashMap91));
        zzbo g100 = a.g(95);
        HashMap hashMap92 = new HashMap();
        hashMap92.put(g100.annotationType(), g100);
        zzaO = new b("onDeviceDocumentDetectionLoadLogEvent", b0.z(hashMap92));
        zzbo g101 = a.g(96);
        HashMap hashMap93 = new HashMap();
        hashMap93.put(g101.annotationType(), g101);
        zzaP = new b("onDeviceDocumentDetectionLogEvent", b0.z(hashMap93));
        zzbo g102 = a.g(97);
        HashMap hashMap94 = new HashMap();
        hashMap94.put(g102.annotationType(), g102);
        zzaQ = new b("aggregatedOnDeviceDocumentDetectionLogEvent", b0.z(hashMap94));
        zzbo g103 = a.g(98);
        HashMap hashMap95 = new HashMap();
        hashMap95.put(g103.annotationType(), g103);
        zzaR = new b("onDeviceDocumentCroppingCreateLogEvent", b0.z(hashMap95));
        zzbo g104 = a.g(99);
        HashMap hashMap96 = new HashMap();
        hashMap96.put(g104.annotationType(), g104);
        zzaS = new b("onDeviceDocumentCroppingLoadLogEvent", b0.z(hashMap96));
        zzbo g105 = a.g(100);
        HashMap hashMap97 = new HashMap();
        hashMap97.put(g105.annotationType(), g105);
        zzaT = new b("onDeviceDocumentCroppingLogEvent", b0.z(hashMap97));
        zzbo g106 = a.g(101);
        HashMap hashMap98 = new HashMap();
        hashMap98.put(g106.annotationType(), g106);
        zzaU = new b("aggregatedOnDeviceDocumentCroppingLogEvent", b0.z(hashMap98));
        zzbo g107 = a.g(102);
        HashMap hashMap99 = new HashMap();
        hashMap99.put(g107.annotationType(), g107);
        zzaV = new b("onDeviceDocumentEnhancementCreateLogEvent", b0.z(hashMap99));
        zzbo g108 = a.g(103);
        HashMap hashMap100 = new HashMap();
        hashMap100.put(g108.annotationType(), g108);
        zzaW = new b("onDeviceDocumentEnhancementLoadLogEvent", b0.z(hashMap100));
        zzbo g109 = a.g(104);
        HashMap hashMap101 = new HashMap();
        hashMap101.put(g109.annotationType(), g109);
        zzaX = new b("onDeviceDocumentEnhancementLogEvent", b0.z(hashMap101));
        zzbo g110 = a.g(105);
        HashMap hashMap102 = new HashMap();
        hashMap102.put(g110.annotationType(), g110);
        zzaY = new b("aggregatedOnDeviceDocumentEnhancementLogEvent", b0.z(hashMap102));
    }

    private zzgh() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzlg zzlg = (zzlg) obj;
        d dVar = (d) obj2;
        dVar.add(zzb, (Object) zzlg.zzf());
        dVar.add(zzc, (Object) zzlg.zzd());
        dVar.add(zzd, (Object) null);
        dVar.add(zze, (Object) null);
        dVar.add(zzf, (Object) zzlg.zze());
        dVar.add(zzg, (Object) null);
        dVar.add(zzh, (Object) null);
        dVar.add(zzi, (Object) null);
        dVar.add(zzj, (Object) null);
        dVar.add(zzk, (Object) null);
        dVar.add(zzl, (Object) null);
        dVar.add(zzm, (Object) null);
        dVar.add(zzn, (Object) null);
        dVar.add(zzo, (Object) null);
        dVar.add(zzp, (Object) null);
        dVar.add(zzq, (Object) null);
        dVar.add(zzr, (Object) null);
        dVar.add(zzs, (Object) null);
        dVar.add(zzt, (Object) null);
        dVar.add(zzu, (Object) null);
        dVar.add(zzv, (Object) null);
        dVar.add(zzw, (Object) null);
        dVar.add(zzx, (Object) null);
        dVar.add(zzy, (Object) null);
        dVar.add(zzz, (Object) null);
        dVar.add(zzA, (Object) null);
        dVar.add(zzB, (Object) null);
        dVar.add(zzC, (Object) null);
        dVar.add(zzD, (Object) null);
        dVar.add(zzE, (Object) null);
        dVar.add(zzF, (Object) null);
        dVar.add(zzG, (Object) null);
        dVar.add(zzH, (Object) null);
        dVar.add(zzI, (Object) null);
        dVar.add(zzJ, (Object) null);
        dVar.add(zzK, (Object) null);
        dVar.add(zzL, (Object) null);
        dVar.add(zzM, (Object) null);
        dVar.add(zzN, (Object) zzlg.zzb());
        dVar.add(zzO, (Object) zzlg.zza());
        dVar.add(zzP, (Object) null);
        dVar.add(zzQ, (Object) null);
        dVar.add(zzR, (Object) null);
        dVar.add(zzS, (Object) null);
        dVar.add(zzT, (Object) null);
        dVar.add(zzU, (Object) null);
        dVar.add(zzV, (Object) null);
        dVar.add(zzW, (Object) null);
        dVar.add(zzX, (Object) null);
        dVar.add(zzY, (Object) null);
        dVar.add(zzZ, (Object) null);
        dVar.add(zzaa, (Object) null);
        dVar.add(zzab, (Object) zzlg.zzc());
        dVar.add(zzac, (Object) null);
        dVar.add(zzad, (Object) null);
        dVar.add(zzae, (Object) null);
        dVar.add(zzaf, (Object) null);
        dVar.add(zzag, (Object) null);
        dVar.add(zzah, (Object) null);
        dVar.add(zzai, (Object) null);
        dVar.add(zzaj, (Object) null);
        dVar.add(zzak, (Object) null);
        dVar.add(zzal, (Object) null);
        dVar.add(zzam, (Object) null);
        dVar.add(zzan, (Object) null);
        dVar.add(zzao, (Object) null);
        dVar.add(zzap, (Object) null);
        dVar.add(zzaq, (Object) null);
        dVar.add(zzar, (Object) null);
        dVar.add(zzas, (Object) null);
        dVar.add(zzat, (Object) null);
        dVar.add(zzau, (Object) null);
        dVar.add(zzav, (Object) null);
        dVar.add(zzaw, (Object) null);
        dVar.add(zzax, (Object) null);
        dVar.add(zzay, (Object) null);
        dVar.add(zzaz, (Object) null);
        dVar.add(zzaA, (Object) null);
        dVar.add(zzaB, (Object) null);
        dVar.add(zzaC, (Object) null);
        dVar.add(zzaD, (Object) null);
        dVar.add(zzaE, (Object) null);
        dVar.add(zzaF, (Object) null);
        dVar.add(zzaG, (Object) null);
        dVar.add(zzaH, (Object) null);
        dVar.add(zzaI, (Object) null);
        dVar.add(zzaJ, (Object) null);
        dVar.add(zzaK, (Object) null);
        dVar.add(zzaL, (Object) null);
        dVar.add(zzaM, (Object) null);
        dVar.add(zzaN, (Object) null);
        dVar.add(zzaO, (Object) null);
        dVar.add(zzaP, (Object) null);
        dVar.add(zzaQ, (Object) null);
        dVar.add(zzaR, (Object) null);
        dVar.add(zzaS, (Object) null);
        dVar.add(zzaT, (Object) null);
        dVar.add(zzaU, (Object) null);
        dVar.add(zzaV, (Object) null);
        dVar.add(zzaW, (Object) null);
        dVar.add(zzaX, (Object) null);
        dVar.add(zzaY, (Object) null);
    }
}
