package com.google.android.gms.internal.mlkit_vision_barcode;

import android.support.v4.media.a;
import f0.b0;
import java.util.HashMap;
import sa.b;
import sa.c;
import sa.d;

/* compiled from: com.google.android.gms:play-services-mlkit-barcode-scanning@@18.2.0 */
final class zzih implements c {
    private static final b zzA;
    private static final b zzB;
    private static final b zzC;
    private static final b zzD;
    private static final b zzE;
    private static final b zzF;
    private static final b zzG;
    private static final b zzH;
    private static final b zzI;
    private static final b zzJ;
    private static final b zzK;
    private static final b zzL;
    private static final b zzM;
    private static final b zzN;
    private static final b zzO;
    private static final b zzP;
    private static final b zzQ;
    private static final b zzR;
    private static final b zzS;
    private static final b zzT;
    private static final b zzU;
    private static final b zzV;
    private static final b zzW;
    private static final b zzX;
    private static final b zzY;
    private static final b zzZ;
    public static final zzih zza = new zzih();
    private static final b zzaA;
    private static final b zzaB;
    private static final b zzaC;
    private static final b zzaD;
    private static final b zzaE;
    private static final b zzaF;
    private static final b zzaG;
    private static final b zzaH;
    private static final b zzaI;
    private static final b zzaJ;
    private static final b zzaK;
    private static final b zzaL;
    private static final b zzaM;
    private static final b zzaN;
    private static final b zzaO;
    private static final b zzaP;
    private static final b zzaQ;
    private static final b zzaR;
    private static final b zzaS;
    private static final b zzaT;
    private static final b zzaU;
    private static final b zzaV;
    private static final b zzaW;
    private static final b zzaX;
    private static final b zzaY;
    private static final b zzaa;
    private static final b zzab;
    private static final b zzac;
    private static final b zzad;
    private static final b zzae;
    private static final b zzaf;
    private static final b zzag;
    private static final b zzah;
    private static final b zzai;
    private static final b zzaj;
    private static final b zzak;
    private static final b zzal;
    private static final b zzam;
    private static final b zzan;
    private static final b zzao;
    private static final b zzap;
    private static final b zzaq;
    private static final b zzar;
    private static final b zzas;
    private static final b zzat;
    private static final b zzau;
    private static final b zzav;
    private static final b zzaw;
    private static final b zzax;
    private static final b zzay;
    private static final b zzaz;
    private static final b zzb;
    private static final b zzc;
    private static final b zzd;
    private static final b zze;
    private static final b zzf;
    private static final b zzg;
    private static final b zzh;
    private static final b zzi;
    private static final b zzj;
    private static final b zzk;
    private static final b zzl;
    private static final b zzm;
    private static final b zzn;
    private static final b zzo;
    private static final b zzp;
    private static final b zzq;
    private static final b zzr;
    private static final b zzs;
    private static final b zzt;
    private static final b zzu;
    private static final b zzv;
    private static final b zzw;
    private static final b zzx;
    private static final b zzy;
    private static final b zzz;

    static {
        zzdk h10 = a.h(1);
        HashMap hashMap = new HashMap();
        hashMap.put(h10.annotationType(), h10);
        zzb = new b("systemInfo", b0.z(hashMap));
        zzdk h11 = a.h(2);
        HashMap hashMap2 = new HashMap();
        hashMap2.put(h11.annotationType(), h11);
        zzc = new b("eventName", b0.z(hashMap2));
        zzdk h12 = a.h(37);
        HashMap hashMap3 = new HashMap();
        hashMap3.put(h12.annotationType(), h12);
        zzd = new b("isThickClient", b0.z(hashMap3));
        zzdk h13 = a.h(61);
        HashMap hashMap4 = new HashMap();
        hashMap4.put(h13.annotationType(), h13);
        zze = new b("clientType", b0.z(hashMap4));
        zzdk h14 = a.h(3);
        HashMap hashMap5 = new HashMap();
        hashMap5.put(h14.annotationType(), h14);
        zzf = new b("modelDownloadLogEvent", b0.z(hashMap5));
        zzdk h15 = a.h(20);
        HashMap hashMap6 = new HashMap();
        hashMap6.put(h15.annotationType(), h15);
        zzg = new b("customModelLoadLogEvent", b0.z(hashMap6));
        zzdk h16 = a.h(4);
        HashMap hashMap7 = new HashMap();
        hashMap7.put(h16.annotationType(), h16);
        zzh = new b("customModelInferenceLogEvent", b0.z(hashMap7));
        zzdk h17 = a.h(29);
        HashMap hashMap8 = new HashMap();
        hashMap8.put(h17.annotationType(), h17);
        zzi = new b("customModelCreateLogEvent", b0.z(hashMap8));
        zzdk h18 = a.h(5);
        HashMap hashMap9 = new HashMap();
        hashMap9.put(h18.annotationType(), h18);
        zzj = new b("onDeviceFaceDetectionLogEvent", b0.z(hashMap9));
        zzdk h19 = a.h(59);
        HashMap hashMap10 = new HashMap();
        hashMap10.put(h19.annotationType(), h19);
        zzk = new b("onDeviceFaceLoadLogEvent", b0.z(hashMap10));
        zzdk h20 = a.h(6);
        HashMap hashMap11 = new HashMap();
        hashMap11.put(h20.annotationType(), h20);
        zzl = new b("onDeviceTextDetectionLogEvent", b0.z(hashMap11));
        zzdk h21 = a.h(79);
        HashMap hashMap12 = new HashMap();
        hashMap12.put(h21.annotationType(), h21);
        zzm = new b("onDeviceTextDetectionLoadLogEvent", b0.z(hashMap12));
        zzdk h22 = a.h(7);
        HashMap hashMap13 = new HashMap();
        hashMap13.put(h22.annotationType(), h22);
        zzn = new b("onDeviceBarcodeDetectionLogEvent", b0.z(hashMap13));
        zzdk h23 = a.h(58);
        HashMap hashMap14 = new HashMap();
        hashMap14.put(h23.annotationType(), h23);
        zzo = new b("onDeviceBarcodeLoadLogEvent", b0.z(hashMap14));
        zzdk h24 = a.h(48);
        HashMap hashMap15 = new HashMap();
        hashMap15.put(h24.annotationType(), h24);
        zzp = new b("onDeviceImageLabelCreateLogEvent", b0.z(hashMap15));
        zzdk h25 = a.h(49);
        HashMap hashMap16 = new HashMap();
        hashMap16.put(h25.annotationType(), h25);
        zzq = new b("onDeviceImageLabelLoadLogEvent", b0.z(hashMap16));
        zzdk h26 = a.h(18);
        HashMap hashMap17 = new HashMap();
        hashMap17.put(h26.annotationType(), h26);
        zzr = new b("onDeviceImageLabelDetectionLogEvent", b0.z(hashMap17));
        zzdk h27 = a.h(26);
        HashMap hashMap18 = new HashMap();
        hashMap18.put(h27.annotationType(), h27);
        zzs = new b("onDeviceObjectCreateLogEvent", b0.z(hashMap18));
        zzdk h28 = a.h(27);
        HashMap hashMap19 = new HashMap();
        hashMap19.put(h28.annotationType(), h28);
        zzt = new b("onDeviceObjectLoadLogEvent", b0.z(hashMap19));
        zzdk h29 = a.h(28);
        HashMap hashMap20 = new HashMap();
        hashMap20.put(h29.annotationType(), h29);
        zzu = new b("onDeviceObjectInferenceLogEvent", b0.z(hashMap20));
        zzdk h30 = a.h(44);
        HashMap hashMap21 = new HashMap();
        hashMap21.put(h30.annotationType(), h30);
        zzv = new b("onDevicePoseDetectionLogEvent", b0.z(hashMap21));
        zzdk h31 = a.h(45);
        HashMap hashMap22 = new HashMap();
        hashMap22.put(h31.annotationType(), h31);
        zzw = new b("onDeviceSegmentationLogEvent", b0.z(hashMap22));
        zzdk h32 = a.h(19);
        HashMap hashMap23 = new HashMap();
        hashMap23.put(h32.annotationType(), h32);
        zzx = new b("onDeviceSmartReplyLogEvent", b0.z(hashMap23));
        zzdk h33 = a.h(21);
        HashMap hashMap24 = new HashMap();
        hashMap24.put(h33.annotationType(), h33);
        zzy = new b("onDeviceLanguageIdentificationLogEvent", b0.z(hashMap24));
        zzdk h34 = a.h(22);
        HashMap hashMap25 = new HashMap();
        hashMap25.put(h34.annotationType(), h34);
        zzz = new b("onDeviceTranslationLogEvent", b0.z(hashMap25));
        zzdk h35 = a.h(8);
        HashMap hashMap26 = new HashMap();
        hashMap26.put(h35.annotationType(), h35);
        zzA = new b("cloudFaceDetectionLogEvent", b0.z(hashMap26));
        zzdk h36 = a.h(9);
        HashMap hashMap27 = new HashMap();
        hashMap27.put(h36.annotationType(), h36);
        zzB = new b("cloudCropHintDetectionLogEvent", b0.z(hashMap27));
        zzdk h37 = a.h(10);
        HashMap hashMap28 = new HashMap();
        hashMap28.put(h37.annotationType(), h37);
        zzC = new b("cloudDocumentTextDetectionLogEvent", b0.z(hashMap28));
        zzdk h38 = a.h(11);
        HashMap hashMap29 = new HashMap();
        hashMap29.put(h38.annotationType(), h38);
        zzD = new b("cloudImagePropertiesDetectionLogEvent", b0.z(hashMap29));
        zzdk h39 = a.h(12);
        HashMap hashMap30 = new HashMap();
        hashMap30.put(h39.annotationType(), h39);
        zzE = new b("cloudImageLabelDetectionLogEvent", b0.z(hashMap30));
        zzdk h40 = a.h(13);
        HashMap hashMap31 = new HashMap();
        hashMap31.put(h40.annotationType(), h40);
        zzF = new b("cloudLandmarkDetectionLogEvent", b0.z(hashMap31));
        zzdk h41 = a.h(14);
        HashMap hashMap32 = new HashMap();
        hashMap32.put(h41.annotationType(), h41);
        zzG = new b("cloudLogoDetectionLogEvent", b0.z(hashMap32));
        zzdk h42 = a.h(15);
        HashMap hashMap33 = new HashMap();
        hashMap33.put(h42.annotationType(), h42);
        zzH = new b("cloudSafeSearchDetectionLogEvent", b0.z(hashMap33));
        zzdk h43 = a.h(16);
        HashMap hashMap34 = new HashMap();
        hashMap34.put(h43.annotationType(), h43);
        zzI = new b("cloudTextDetectionLogEvent", b0.z(hashMap34));
        zzdk h44 = a.h(17);
        HashMap hashMap35 = new HashMap();
        hashMap35.put(h44.annotationType(), h44);
        zzJ = new b("cloudWebSearchDetectionLogEvent", b0.z(hashMap35));
        zzdk h45 = a.h(23);
        HashMap hashMap36 = new HashMap();
        hashMap36.put(h45.annotationType(), h45);
        zzK = new b("automlImageLabelingCreateLogEvent", b0.z(hashMap36));
        zzdk h46 = a.h(24);
        HashMap hashMap37 = new HashMap();
        hashMap37.put(h46.annotationType(), h46);
        zzL = new b("automlImageLabelingLoadLogEvent", b0.z(hashMap37));
        zzdk h47 = a.h(25);
        HashMap hashMap38 = new HashMap();
        hashMap38.put(h47.annotationType(), h47);
        zzM = new b("automlImageLabelingInferenceLogEvent", b0.z(hashMap38));
        zzdk h48 = a.h(39);
        HashMap hashMap39 = new HashMap();
        hashMap39.put(h48.annotationType(), h48);
        zzN = new b("isModelDownloadedLogEvent", b0.z(hashMap39));
        zzdk h49 = a.h(40);
        HashMap hashMap40 = new HashMap();
        hashMap40.put(h49.annotationType(), h49);
        zzO = new b("deleteModelLogEvent", b0.z(hashMap40));
        zzdk h50 = a.h(30);
        HashMap hashMap41 = new HashMap();
        hashMap41.put(h50.annotationType(), h50);
        zzP = new b("aggregatedAutomlImageLabelingInferenceLogEvent", b0.z(hashMap41));
        zzdk h51 = a.h(31);
        HashMap hashMap42 = new HashMap();
        hashMap42.put(h51.annotationType(), h51);
        zzQ = new b("aggregatedCustomModelInferenceLogEvent", b0.z(hashMap42));
        zzdk h52 = a.h(32);
        HashMap hashMap43 = new HashMap();
        hashMap43.put(h52.annotationType(), h52);
        zzR = new b("aggregatedOnDeviceFaceDetectionLogEvent", b0.z(hashMap43));
        zzdk h53 = a.h(33);
        HashMap hashMap44 = new HashMap();
        hashMap44.put(h53.annotationType(), h53);
        zzS = new b("aggregatedOnDeviceBarcodeDetectionLogEvent", b0.z(hashMap44));
        zzdk h54 = a.h(34);
        HashMap hashMap45 = new HashMap();
        hashMap45.put(h54.annotationType(), h54);
        zzT = new b("aggregatedOnDeviceImageLabelDetectionLogEvent", b0.z(hashMap45));
        zzdk h55 = a.h(35);
        HashMap hashMap46 = new HashMap();
        hashMap46.put(h55.annotationType(), h55);
        zzU = new b("aggregatedOnDeviceObjectInferenceLogEvent", b0.z(hashMap46));
        zzdk h56 = a.h(36);
        HashMap hashMap47 = new HashMap();
        hashMap47.put(h56.annotationType(), h56);
        zzV = new b("aggregatedOnDeviceTextDetectionLogEvent", b0.z(hashMap47));
        zzdk h57 = a.h(46);
        HashMap hashMap48 = new HashMap();
        hashMap48.put(h57.annotationType(), h57);
        zzW = new b("aggregatedOnDevicePoseDetectionLogEvent", b0.z(hashMap48));
        zzdk h58 = a.h(47);
        HashMap hashMap49 = new HashMap();
        hashMap49.put(h58.annotationType(), h58);
        zzX = new b("aggregatedOnDeviceSegmentationLogEvent", b0.z(hashMap49));
        zzdk h59 = a.h(69);
        HashMap hashMap50 = new HashMap();
        hashMap50.put(h59.annotationType(), h59);
        zzY = new b("pipelineAccelerationInferenceEvents", b0.z(hashMap50));
        zzdk h60 = a.h(42);
        HashMap hashMap51 = new HashMap();
        hashMap51.put(h60.annotationType(), h60);
        zzZ = new b("remoteConfigLogEvent", b0.z(hashMap51));
        zzdk h61 = a.h(50);
        HashMap hashMap52 = new HashMap();
        hashMap52.put(h61.annotationType(), h61);
        zzaa = new b("inputImageConstructionLogEvent", b0.z(hashMap52));
        zzdk h62 = a.h(51);
        HashMap hashMap53 = new HashMap();
        hashMap53.put(h62.annotationType(), h62);
        zzab = new b("leakedHandleEvent", b0.z(hashMap53));
        zzdk h63 = a.h(52);
        HashMap hashMap54 = new HashMap();
        hashMap54.put(h63.annotationType(), h63);
        zzac = new b("cameraSourceLogEvent", b0.z(hashMap54));
        zzdk h64 = a.h(53);
        HashMap hashMap55 = new HashMap();
        hashMap55.put(h64.annotationType(), h64);
        zzad = new b("imageLabelOptionalModuleLogEvent", b0.z(hashMap55));
        zzdk h65 = a.h(54);
        HashMap hashMap56 = new HashMap();
        hashMap56.put(h65.annotationType(), h65);
        zzae = new b("languageIdentificationOptionalModuleLogEvent", b0.z(hashMap56));
        zzdk h66 = a.h(60);
        HashMap hashMap57 = new HashMap();
        hashMap57.put(h66.annotationType(), h66);
        zzaf = new b("faceDetectionOptionalModuleLogEvent", b0.z(hashMap57));
        zzdk h67 = a.h(85);
        HashMap hashMap58 = new HashMap();
        hashMap58.put(h67.annotationType(), h67);
        zzag = new b("documentDetectionOptionalModuleLogEvent", b0.z(hashMap58));
        zzdk h68 = a.h(86);
        HashMap hashMap59 = new HashMap();
        hashMap59.put(h68.annotationType(), h68);
        zzah = new b("documentCroppingOptionalModuleLogEvent", b0.z(hashMap59));
        zzdk h69 = a.h(87);
        HashMap hashMap60 = new HashMap();
        hashMap60.put(h69.annotationType(), h69);
        zzai = new b("documentEnhancementOptionalModuleLogEvent", b0.z(hashMap60));
        zzdk h70 = a.h(55);
        HashMap hashMap61 = new HashMap();
        hashMap61.put(h70.annotationType(), h70);
        zzaj = new b("nlClassifierOptionalModuleLogEvent", b0.z(hashMap61));
        zzdk h71 = a.h(56);
        HashMap hashMap62 = new HashMap();
        hashMap62.put(h71.annotationType(), h71);
        zzak = new b("nlClassifierClientLibraryLogEvent", b0.z(hashMap62));
        zzdk h72 = a.h(57);
        HashMap hashMap63 = new HashMap();
        hashMap63.put(h72.annotationType(), h72);
        zzal = new b("accelerationAllowlistLogEvent", b0.z(hashMap63));
        zzdk h73 = a.h(62);
        HashMap hashMap64 = new HashMap();
        hashMap64.put(h73.annotationType(), h73);
        zzam = new b("toxicityDetectionCreateEvent", b0.z(hashMap64));
        zzdk h74 = a.h(63);
        HashMap hashMap65 = new HashMap();
        hashMap65.put(h74.annotationType(), h74);
        zzan = new b("toxicityDetectionLoadEvent", b0.z(hashMap65));
        zzdk h75 = a.h(64);
        HashMap hashMap66 = new HashMap();
        hashMap66.put(h75.annotationType(), h75);
        zzao = new b("toxicityDetectionInferenceEvent", b0.z(hashMap66));
        zzdk h76 = a.h(65);
        HashMap hashMap67 = new HashMap();
        hashMap67.put(h76.annotationType(), h76);
        zzap = new b("barcodeDetectionOptionalModuleLogEvent", b0.z(hashMap67));
        zzdk h77 = a.h(66);
        HashMap hashMap68 = new HashMap();
        hashMap68.put(h77.annotationType(), h77);
        zzaq = new b("customImageLabelOptionalModuleLogEvent", b0.z(hashMap68));
        zzdk h78 = a.h(67);
        HashMap hashMap69 = new HashMap();
        hashMap69.put(h78.annotationType(), h78);
        zzar = new b("codeScannerScanApiEvent", b0.z(hashMap69));
        zzdk h79 = a.h(68);
        HashMap hashMap70 = new HashMap();
        hashMap70.put(h79.annotationType(), h79);
        zzas = new b("codeScannerOptionalModuleEvent", b0.z(hashMap70));
        zzdk h80 = a.h(70);
        HashMap hashMap71 = new HashMap();
        hashMap71.put(h80.annotationType(), h80);
        zzat = new b("onDeviceExplicitContentCreateLogEvent", b0.z(hashMap71));
        zzdk h81 = a.h(71);
        HashMap hashMap72 = new HashMap();
        hashMap72.put(h81.annotationType(), h81);
        zzau = new b("onDeviceExplicitContentLoadLogEvent", b0.z(hashMap72));
        zzdk h82 = a.h(72);
        HashMap hashMap73 = new HashMap();
        hashMap73.put(h82.annotationType(), h82);
        zzav = new b("onDeviceExplicitContentInferenceLogEvent", b0.z(hashMap73));
        zzdk h83 = a.h(73);
        HashMap hashMap74 = new HashMap();
        hashMap74.put(h83.annotationType(), h83);
        zzaw = new b("aggregatedOnDeviceExplicitContentLogEvent", b0.z(hashMap74));
        zzdk h84 = a.h(74);
        HashMap hashMap75 = new HashMap();
        hashMap75.put(h84.annotationType(), h84);
        zzax = new b("onDeviceFaceMeshCreateLogEvent", b0.z(hashMap75));
        zzdk h85 = a.h(75);
        HashMap hashMap76 = new HashMap();
        hashMap76.put(h85.annotationType(), h85);
        zzay = new b("onDeviceFaceMeshLoadLogEvent", b0.z(hashMap76));
        zzdk h86 = a.h(76);
        HashMap hashMap77 = new HashMap();
        hashMap77.put(h86.annotationType(), h86);
        zzaz = new b("onDeviceFaceMeshLogEvent", b0.z(hashMap77));
        zzdk h87 = a.h(77);
        HashMap hashMap78 = new HashMap();
        hashMap78.put(h87.annotationType(), h87);
        zzaA = new b("aggregatedOnDeviceFaceMeshLogEvent", b0.z(hashMap78));
        zzdk h88 = a.h(78);
        HashMap hashMap79 = new HashMap();
        hashMap79.put(h88.annotationType(), h88);
        zzaB = new b("smartReplyOptionalModuleLogEvent", b0.z(hashMap79));
        zzdk h89 = a.h(80);
        HashMap hashMap80 = new HashMap();
        hashMap80.put(h89.annotationType(), h89);
        zzaC = new b("textDetectionOptionalModuleLogEvent", b0.z(hashMap80));
        zzdk h90 = a.h(81);
        HashMap hashMap81 = new HashMap();
        hashMap81.put(h90.annotationType(), h90);
        zzaD = new b("onDeviceImageQualityAnalysisCreateLogEvent", b0.z(hashMap81));
        zzdk h91 = a.h(82);
        HashMap hashMap82 = new HashMap();
        hashMap82.put(h91.annotationType(), h91);
        zzaE = new b("onDeviceImageQualityAnalysisLoadLogEvent", b0.z(hashMap82));
        zzdk h92 = a.h(83);
        HashMap hashMap83 = new HashMap();
        hashMap83.put(h92.annotationType(), h92);
        zzaF = new b("onDeviceImageQualityAnalysisLogEvent", b0.z(hashMap83));
        zzdk h93 = a.h(84);
        HashMap hashMap84 = new HashMap();
        hashMap84.put(h93.annotationType(), h93);
        zzaG = new b("aggregatedOnDeviceImageQualityAnalysisLogEvent", b0.z(hashMap84));
        zzdk h94 = a.h(88);
        HashMap hashMap85 = new HashMap();
        hashMap85.put(h94.annotationType(), h94);
        zzaH = new b("imageQualityAnalysisOptionalModuleLogEvent", b0.z(hashMap85));
        zzdk h95 = a.h(89);
        HashMap hashMap86 = new HashMap();
        hashMap86.put(h95.annotationType(), h95);
        zzaI = new b("imageCaptioningOptionalModuleLogEvent", b0.z(hashMap86));
        zzdk h96 = a.h(90);
        HashMap hashMap87 = new HashMap();
        hashMap87.put(h96.annotationType(), h96);
        zzaJ = new b("onDeviceImageCaptioningCreateLogEvent", b0.z(hashMap87));
        zzdk h97 = a.h(91);
        HashMap hashMap88 = new HashMap();
        hashMap88.put(h97.annotationType(), h97);
        zzaK = new b("onDeviceImageCaptioningLoadLogEvent", b0.z(hashMap88));
        zzdk h98 = a.h(92);
        HashMap hashMap89 = new HashMap();
        hashMap89.put(h98.annotationType(), h98);
        zzaL = new b("onDeviceImageCaptioningInferenceLogEvent", b0.z(hashMap89));
        zzdk h99 = a.h(93);
        HashMap hashMap90 = new HashMap();
        hashMap90.put(h99.annotationType(), h99);
        zzaM = new b("aggregatedOnDeviceImageCaptioningInferenceLogEvent", b0.z(hashMap90));
        zzdk h100 = a.h(94);
        HashMap hashMap91 = new HashMap();
        hashMap91.put(h100.annotationType(), h100);
        zzaN = new b("onDeviceDocumentDetectionCreateLogEvent", b0.z(hashMap91));
        zzdk h101 = a.h(95);
        HashMap hashMap92 = new HashMap();
        hashMap92.put(h101.annotationType(), h101);
        zzaO = new b("onDeviceDocumentDetectionLoadLogEvent", b0.z(hashMap92));
        zzdk h102 = a.h(96);
        HashMap hashMap93 = new HashMap();
        hashMap93.put(h102.annotationType(), h102);
        zzaP = new b("onDeviceDocumentDetectionLogEvent", b0.z(hashMap93));
        zzdk h103 = a.h(97);
        HashMap hashMap94 = new HashMap();
        hashMap94.put(h103.annotationType(), h103);
        zzaQ = new b("aggregatedOnDeviceDocumentDetectionLogEvent", b0.z(hashMap94));
        zzdk h104 = a.h(98);
        HashMap hashMap95 = new HashMap();
        hashMap95.put(h104.annotationType(), h104);
        zzaR = new b("onDeviceDocumentCroppingCreateLogEvent", b0.z(hashMap95));
        zzdk h105 = a.h(99);
        HashMap hashMap96 = new HashMap();
        hashMap96.put(h105.annotationType(), h105);
        zzaS = new b("onDeviceDocumentCroppingLoadLogEvent", b0.z(hashMap96));
        zzdk h106 = a.h(100);
        HashMap hashMap97 = new HashMap();
        hashMap97.put(h106.annotationType(), h106);
        zzaT = new b("onDeviceDocumentCroppingLogEvent", b0.z(hashMap97));
        zzdk h107 = a.h(101);
        HashMap hashMap98 = new HashMap();
        hashMap98.put(h107.annotationType(), h107);
        zzaU = new b("aggregatedOnDeviceDocumentCroppingLogEvent", b0.z(hashMap98));
        zzdk h108 = a.h(102);
        HashMap hashMap99 = new HashMap();
        hashMap99.put(h108.annotationType(), h108);
        zzaV = new b("onDeviceDocumentEnhancementCreateLogEvent", b0.z(hashMap99));
        zzdk h109 = a.h(103);
        HashMap hashMap100 = new HashMap();
        hashMap100.put(h109.annotationType(), h109);
        zzaW = new b("onDeviceDocumentEnhancementLoadLogEvent", b0.z(hashMap100));
        zzdk h110 = a.h(104);
        HashMap hashMap101 = new HashMap();
        hashMap101.put(h110.annotationType(), h110);
        zzaX = new b("onDeviceDocumentEnhancementLogEvent", b0.z(hashMap101));
        zzdk h111 = a.h(105);
        HashMap hashMap102 = new HashMap();
        hashMap102.put(h111.annotationType(), h111);
        zzaY = new b("aggregatedOnDeviceDocumentEnhancementLogEvent", b0.z(hashMap102));
    }

    private zzih() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zznh zznh = (zznh) obj;
        d dVar = (d) obj2;
        dVar.add(zzb, (Object) zznh.zzf());
        dVar.add(zzc, (Object) zznh.zzc());
        dVar.add(zzd, (Object) null);
        dVar.add(zze, (Object) zznh.zzb());
        dVar.add(zzf, (Object) null);
        dVar.add(zzg, (Object) null);
        dVar.add(zzh, (Object) null);
        dVar.add(zzi, (Object) null);
        dVar.add(zzj, (Object) null);
        dVar.add(zzk, (Object) null);
        dVar.add(zzl, (Object) null);
        dVar.add(zzm, (Object) null);
        dVar.add(zzn, (Object) zznh.zzd());
        dVar.add(zzo, (Object) zznh.zze());
        dVar.add(zzp, (Object) null);
        dVar.add(zzq, (Object) null);
        dVar.add(zzr, (Object) null);
        dVar.add(zzs, (Object) null);
        dVar.add(zzt, (Object) null);
        dVar.add(zzu, (Object) null);
        dVar.add(zzv, (Object) null);
        dVar.add(zzw, (Object) null);
        dVar.add(zzx, (Object) null);
        dVar.add(zzy, (Object) null);
        dVar.add(zzz, (Object) null);
        dVar.add(zzA, (Object) null);
        dVar.add(zzB, (Object) null);
        dVar.add(zzC, (Object) null);
        dVar.add(zzD, (Object) null);
        dVar.add(zzE, (Object) null);
        dVar.add(zzF, (Object) null);
        dVar.add(zzG, (Object) null);
        dVar.add(zzH, (Object) null);
        dVar.add(zzI, (Object) null);
        dVar.add(zzJ, (Object) null);
        dVar.add(zzK, (Object) null);
        dVar.add(zzL, (Object) null);
        dVar.add(zzM, (Object) null);
        dVar.add(zzN, (Object) null);
        dVar.add(zzO, (Object) null);
        dVar.add(zzP, (Object) null);
        dVar.add(zzQ, (Object) null);
        dVar.add(zzR, (Object) null);
        dVar.add(zzS, (Object) zznh.zza());
        dVar.add(zzT, (Object) null);
        dVar.add(zzU, (Object) null);
        dVar.add(zzV, (Object) null);
        dVar.add(zzW, (Object) null);
        dVar.add(zzX, (Object) null);
        dVar.add(zzY, (Object) null);
        dVar.add(zzZ, (Object) null);
        dVar.add(zzaa, (Object) null);
        dVar.add(zzab, (Object) null);
        dVar.add(zzac, (Object) null);
        dVar.add(zzad, (Object) null);
        dVar.add(zzae, (Object) null);
        dVar.add(zzaf, (Object) null);
        dVar.add(zzag, (Object) null);
        dVar.add(zzah, (Object) null);
        dVar.add(zzai, (Object) null);
        dVar.add(zzaj, (Object) null);
        dVar.add(zzak, (Object) null);
        dVar.add(zzal, (Object) null);
        dVar.add(zzam, (Object) null);
        dVar.add(zzan, (Object) null);
        dVar.add(zzao, (Object) null);
        dVar.add(zzap, (Object) null);
        dVar.add(zzaq, (Object) null);
        dVar.add(zzar, (Object) null);
        dVar.add(zzas, (Object) null);
        dVar.add(zzat, (Object) null);
        dVar.add(zzau, (Object) null);
        dVar.add(zzav, (Object) null);
        dVar.add(zzaw, (Object) null);
        dVar.add(zzax, (Object) null);
        dVar.add(zzay, (Object) null);
        dVar.add(zzaz, (Object) null);
        dVar.add(zzaA, (Object) null);
        dVar.add(zzaB, (Object) null);
        dVar.add(zzaC, (Object) null);
        dVar.add(zzaD, (Object) null);
        dVar.add(zzaE, (Object) null);
        dVar.add(zzaF, (Object) null);
        dVar.add(zzaG, (Object) null);
        dVar.add(zzaH, (Object) null);
        dVar.add(zzaI, (Object) null);
        dVar.add(zzaJ, (Object) null);
        dVar.add(zzaK, (Object) null);
        dVar.add(zzaL, (Object) null);
        dVar.add(zzaM, (Object) null);
        dVar.add(zzaN, (Object) null);
        dVar.add(zzaO, (Object) null);
        dVar.add(zzaP, (Object) null);
        dVar.add(zzaQ, (Object) null);
        dVar.add(zzaR, (Object) null);
        dVar.add(zzaS, (Object) null);
        dVar.add(zzaT, (Object) null);
        dVar.add(zzaU, (Object) null);
        dVar.add(zzaV, (Object) null);
        dVar.add(zzaW, (Object) null);
        dVar.add(zzaX, (Object) null);
        dVar.add(zzaY, (Object) null);
    }
}
